# Pre-processing of the dataset GoEmotion

In [15]:
#!pip install pandas
#!pip install datasets
#!pip install nltk
#nltl.download()

In [2]:
from datasets import load_dataset
import pandas as pd
#import nltk
from Utility import clean_dataset

#nltk.download('punkt')
#nltk.download('stopwords')

ds = load_dataset("google-research-datasets/go_emotions", "simplified")
ds_train = ds['train'].to_pandas()
ds_test = ds['test'].to_pandas()
ds = pd.concat([ds_train, ds_test])
print(ds.head())
print(ds.shape)

                                                text labels       id
0  My favourite food is anything I didn't have to...   [27]  eebbqej
1  Now if he does off himself, everyone will thin...   [27]  ed00q6i
2                     WHY THE FUCK IS BAYLESS ISOING    [2]  eezlygj
3                        To make her feel threatened   [14]  ed7ypvh
4                             Dirty Southern Wankers    [3]  ed0bdzj
(48837, 3)

In [3]:
emotion = { 0 : 'admiration',
            1 : 'amusement',
            2 : 'anger',
            3 : 'annoyance' ,
            4 : 'approval' ,
            5 : 'caring' ,
            6 : 'confusion',
            7 : 'curiosity',
            8 : 'desire',
            9 : 'disappointment',
            10: 'disapproval' ,
            11: 'disgust',
            12: 'embarrassment',
            13: 'excitement',
            14: 'fear',
            15: 'gratitude',
            16: 'grief',
            17: 'joy',
            18: 'love',
            19: 'nervousness',
            20: 'optimism',
            21: 'pride',
            22: 'realization',
            23: 'relief',
            24: 'remorse',
            25: 'sadness',
            26: 'surprise',
            27: 'neutral'}

#Ekman representation
ekman_emotion = { "angry": ["anger", "annoyance", "disapproval"],
                  "disgust": ["disgust"],
                  "fear": ["fear", "nervousness"],
                  "happy": ["joy", "amusement", "approval", "excitement", "gratitude",  "love", "optimism", "relief", "pride", "admiration", "desire", "caring"],
                  "sad": ["sadness", "disappointment", "embarrassment", "grief",  "remorse"],
                  "surprise": ["surprise", "realization", "confusion", "curiosity"],
                  "neutral": ["neutral"]
}

label_proccesed = []
for label in ds['labels']:
    label_proccesed.append(emotion[int(label[0])])

labels = []
for label in label_proccesed:
    for key, value in ekman_emotion.items():
        if label in value:
            labels.append(key)

ds['labels'] = labels
ds

                                                   text   labels       id
0     My favourite food is anything I didn't have to...  neutral  eebbqej
1     Now if he does off himself, everyone will thin...  neutral  ed00q6i
2                        WHY THE FUCK IS BAYLESS ISOING    angry  eezlygj
3                           To make her feel threatened     fear  ed7ypvh
4                                Dirty Southern Wankers    angry  ed0bdzj
...                                                 ...      ...      ...
5422  Thanks. I was diagnosed with BP 1 after the ho...    happy  efeeasc
5423                             Well that makes sense.    happy  ef9c7s3
5424                                Daddy issues [NAME]  neutral  efbiugo
5425  So glad I discovered that subreddit a couple m...    happy  efbvgp9
5426  Had to watch "Elmo in Grouchland" one time too...  neutral  edtjpv6

[48837 rows x 3 columns]

In [4]:
ds = ds.drop('id', axis=1)
ds

                                                   text   labels
0     My favourite food is anything I didn't have to...  neutral
1     Now if he does off himself, everyone will thin...  neutral
2                        WHY THE FUCK IS BAYLESS ISOING    angry
3                           To make her feel threatened     fear
4                                Dirty Southern Wankers    angry
...                                                 ...      ...
5422  Thanks. I was diagnosed with BP 1 after the ho...    happy
5423                             Well that makes sense.    happy
5424                                Daddy issues [NAME]  neutral
5425  So glad I discovered that subreddit a couple m...    happy
5426  Had to watch "Elmo in Grouchland" one time too...  neutral

[48837 rows x 2 columns]

In [5]:
texts = clean_dataset(ds)
ds['text'] = texts
ds

                                                   text   labels
0                    favourite food anything didnt cook  neutral
1     everyone think hes laugh screwing people inste...  neutral
2                                   fuck bayless isoing    angry
3                                  make feel threatened     fear
4                                dirty southern wankers    angry
...                                                 ...      ...
5422         thanks diagnosed bp 1 hospitalization well    happy
5423                                   well makes sense    happy
5424                                       daddy issues  neutral
5425   glad discovered subreddit couple months ago good    happy
5426  watch elmo grouchland one time many kids littl...  neutral

[48837 rows x 2 columns]

In [6]:
ds['labels'].value_counts(sort=True)

labels
happy       19002
neutral     14429
angry        6039
surprise     5062
sad          2936
fear          705
disgust       664
Name: count, dtype: int64

In [7]:
ds.to_csv('Text_Dataset_Ekman_Tokenized.csv', index=False)

In [22]:
ds.shape

(48837, 2)